version: '3'
services:
  db:
    image: postgres
    volumes:
      - psgl_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/todo
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  psgl_data:
